- name: composer
  src: geerlingguy.composer

- name: ntp
  src: resmo.ntp

- name: logrotate
  src: nickhammond.logrotate

- name: swapfile
  src: kamaln7.swapfile

- src: geerlingguy.daemonize

- name: mailhog
  src: geerlingguy.mailhog

- name: vsftpd
  src: infOpen.vsftpd