---

# Tasks about configuration checks
- name: Check listen(_ipv6) keys because they are mutually exclusive
  fail:
    msg: 'Listen and listen_ipv6 are mutually exclusive'
  when:
    - vsftpd_listen
    - vsftpd_listen_ipv6

