---

- name: Create additional files directories
  become: True
  file:
    dest: "{{ item | dirname }}"
    owner: "{{ vsftpd_additional_directories_owner }}"
    group: "{{ vsftpd_additional_directories_group }}"
    mode: "{{ vsftpd_additional_directories_mode }}"
    state: directory
  with_items:
    - "{{ vsftpd_ca_certs_file }}"
    - "{{ vsftpd_dsa_cert_file }}"
    - "{{ vsftpd_dsa_private_key_file }}"
    - "{{ vsftpd_rsa_cert_file }}"
    - "{{ vsftpd_rsa_private_key_file }}"
    - "{{ vsftpd_banned_email_file }}"
    - "{{ vsftpd_banner_file }}"
    - "{{ vsftpd_chroot_list_file }}"
    - "{{ vsftpd_email_password_file }}"
    - "{{ vsftpd_userlist_file }}"
    - "{{ vsftpd_pam_configuration_file }}"
  when: item and (item|dirname != '') and (item|dirname != '/')


- name: Create additional files with their content if needed
  become: True
  copy:
    content: "{{ item.1 }}"
    dest: "{{ item.0 }}"
    owner: "{{ vsftpd_additional_files_owner }}"
    group: "{{ vsftpd_additional_files_group }}"
    mode: "{{ vsftpd_additional_files_mode }}"
  with_together:
    - [
        "{{ vsftpd_ca_certs_file }}",
        "{{ vsftpd_dsa_cert_file }}",
        "{{ vsftpd_dsa_private_key_file }}",
        "{{ vsftpd_rsa_cert_file }}",
        "{{ vsftpd_rsa_private_key_file }}",
        "{{ vsftpd_banned_email_file }}",
        "{{ vsftpd_banner_file }}",
        "{{ vsftpd_chroot_list_file }}",
        "{{ vsftpd_email_password_file }}",
        "{{ vsftpd_userlist_file }}",
        "{{ vsftpd_pam_configuration_file }}"
      ]
    - [
        "{{ vsftpd_ca_certs_file_content }}",
        "{{ vsftpd_dsa_cert_file_content }}",
        "{{ vsftpd_dsa_private_key_file_content }}",
        "{{ vsftpd_rsa_cert_file_content }}",
        "{{ vsftpd_rsa_private_key_file_content }}",
        "{{ vsftpd_banned_email_file_content }}",
        "{{ vsftpd_banner_file_content }}",
        "{{ vsftpd_chroot_list_file_content }}",
        "{{ vsftpd_email_password_file_content }}",
        "{{ vsftpd_userlist_file_content }}",
        "{{ vsftpd_pam_configuration_file_content }}"
      ]
  when: item.0
  notify: restart vsftpd

