---

- name: install vsftpd packages
  become: True
  apt:
    name: "{{ item }}"
    state: "{{ vsftpd_package_state }}"
    update_cache: True
    cache_valid_time: 3600
  with_items: "{{ vsftpd_packages }}"
  notify:
    - restart vsftpd

